version: "3.8"

networks:
  raynet:
    driver: overlay
    attachable: true

services:
  captain:
    image: ${REGISTRY}/canoe:tmp
    entrypoint: ["/bin/bash"]
    user: "${USER_UID}:${USER_GID}"
    networks:
      - raynet
    # args: run_command, master_addr, node_rank, proc_per_node, nodes
    command: ['run.sh', 'captain', '0', '2', '3']
    deploy:
      restart_policy:
        condition: none
      resources:
        reservations:
          generic_resources:
            - discrete_resource_spec:
                kind: gpu
                value: 2
      replicas: 1
      placement:
        constraints:
          - node.labels.role == captain
    environment:
      - USERNAME=${USER}
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      - NVIDIA_VISIBLE_DEVICES=all
      - NCCL_SOCKET_IFNAME=eth0
    volumes:
      - .:/work
      - /mnt/data1/cli/2026.SubNeptune:/data
    working_dir: /work

  crew1:
    image: ${REGISTRY}/canoe:tmp
    entrypoint: ["/bin/bash"]
    user: "${USER_UID}:${USER_GID}"
    networks:
      - raynet
    # args: run_command, master_addr, node_rank, proc_per_node, nodes
    command: ['run.sh', 'captain', '1', '2', '3']
    deploy:
      restart_policy:
        condition: none
      resources:
        reservations:
          generic_resources:
            - discrete_resource_spec:
                kind: gpu
                value: 2
      replicas: 1
      placement:
        constraints:
          - node.labels.role == crew
    environment:
      - USERNAME=${USER}
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      - NVIDIA_VISIBLE_DEVICES=all
      - NCCL_SOCKET_IFNAME=eth0
    volumes:
      - .:/work
      - /mnt/data1/cli/2026.SubNeptune:/data
    working_dir: /work

  crew2:
    image: ${REGISTRY}/canoe:tmp
    entrypoint: ["/bin/bash"]
    user: "${USER_UID}:${USER_GID}"
    networks:
      - raynet
    # args: run_command, master_addr, node_rank, proc_per_node, nodes
    command: ['run.sh', 'captain', '2', '2', '3']
    deploy:
      restart_policy:
        condition: none
      resources:
        reservations:
          generic_resources:
            - discrete_resource_spec:
                kind: gpu
                value: 2
      replicas: 1
      placement:
        constraints:
          - node.labels.role == crew
    environment:
      - USERNAME=${USER}
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      - NVIDIA_VISIBLE_DEVICES=all
      - NCCL_SOCKET_IFNAME=eth0
    volumes:
      - .:/work
      - /mnt/data1/cli/2026.SubNeptune:/data
    working_dir: /work
